"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
# -- coding: UTF-8 --
__author__ = 'Mateusz'


def problem2(maxfibvalue):
    fib = [1, 2]
    i = 2
    total = 0
    while True:
        fib.append(fib[i - 1] + fib[i - 2])
        if fib[i] > maxfibvalue:
            fib.pop()
            break
        else:
            i += 1
    for i in range(0, len(fib)):
        if fib[i] % 2 == 0:
            total += fib[i]
    return total

print problem2(4000000)
# Output: 4613732